### ISSUE TITLE
Timeentry support

### ISSUE THREAD

**Issue by christianwiedemann** [freshheads/harvest-api-client#2]
Hi,

I would like to use your api client with time entries. 
Would you welcome a pr?

**Comment by jvandesande** [comment]
Hi @christianwiedemann,

You can already use the (plain) Client to create and query time entries. But you're welcome to send a PR for a TimeEntry endpoint.
See the ClientEndpoint for an example:
https://github.com/freshheads/harvest-api-client/blob/develop/src/Endpoint/ClientEndpoint.php

The library is under heavy development at our side, that's why there is no stable version at the moment. If you take this into account and you're willing to help, I would like to see your PR :).

**Comment by jvandesande** [comment]
Time entry support is added via https://github.com/freshheads/harvest-api-client/commit/7d9eef87ff014351731595ba9de85a9874b1525f
